### ISSUE TITLE
File differ

### ISSUE THREAD

**Issue by bilginyuksel** [Zeevac/File-Differ#1]
Hello, I tried the application and tested a little bit. According to my tests I see when I compare two files the application excepts every line as a new line created. I think the application should store one files information then compare with the other or others. I mean it should be like `testfile1.txt diff testfile2.txt`. Don't get confused I am not talking about the usage on CLI I am talking about the idea.

**Comment by safayildirim** [comment]
Thank you for your reply Kaan. I will consider your suggestion. Btw this is a first commit and basic concept of what the app should do.
